#ifndef CHATBOTDIALOG_H
#define CHATBOTDIALOG_H

#include <QDialog>

class ChatBot;
class Service;

namespace Ui {
class ChatBotDialog;
}

class ChatBotDialog : public QDialog
{
    Q_OBJECT

public:
    explicit ChatBotDialog(Service *serviceManager, QWidget *parent = nullptr);
    ~ChatBotDialog();

private slots:
    // Slot to handle user input when the send button is clicked
    void onSendButtonClicked();

private:
    Ui::ChatBotDialog *ui;         // Pointer to the UI generated by Qt Designer
    ChatBot *chatbotInstance;      // Instance of the ChatBot class
};

#endif // CHATBOTDIALOG_H
